var characters = ['Luke', 'Leia', 'Han', 'Chewie']

console.log(characters)
console.log(characters.length)
console.log(characters[characters.length - 1])
characters.push('Davis')
characters.push('Wandi')
console.log(characters)
characters.pop()
console.log(characters)
characters.unshift('bwake')
characters.unshift('ninja')
console.log(characters)
characters.shift('ninja')
console.log(characters)
