let characters = ['Luke', 'Leia', 'Han', 'Chewie']
console.log(characters)
characters.splice(0, 1, 'Ray')
console.log(characters)
characters.splice(1,2,'Kylo')
console.log(characters)
characters.splice(1,1,'davis','bwake')
console.log(characters)
characters.splice(1,2)
console.log(characters)
characters.push('Alex','max','stacey', 'harriet')
console.log(characters)
characters.reverse()
console.log(characters)
characters.sort()
console.log(characters)
console.log(characters.indexOf('Luke'))
console.log(characters.indexOf('Ray'))
console.log(characters.lastIndexOf('Luke'))
console.log(characters.lastIndexOf('Ray'))